target_sources(map
    PRIVATE
    achievement.c
    atcommand.c
    battle.c
    battleground.c
    buyingstore.c
    channel.c
    chat.c
    chrif.c
    clan.c
    clif.c
    date.c
    duel.c
    elemental.c
    guild.c
    homunculus.c
    HPMmap.c
    instance.c
    intif.c
    irc-bot.c
    itemdb.c
    log.c
    mail.c
    map.c
    mapreg_sql.c
    mercenary.c
    mob.c
    npc.c
    npc_chat.c
    party.c
    path.c
    pc.c
    pc_groups.c
    pet.c
    quest.c
    refine.c
    rodex.c
    script.c
    searchstore.c
    skill.c
    status.c
    storage.c
    stylist.c
    trade.c
    unit.c
    vending.c
    achievement.h
    atcommand.h
    battleground.h
    battle.h
    buyingstore.h
    channel.h
    chat.h
    chrif.h
    clan.h
    clif.h
    date.h
    duel.h
    elemental.h
    guild.h
    homunculus.h
    HPMmap.h
    instance.h
    intif.h
    irc-bot.h
    itemdb.h
    log.h
    mail.h
    mapdefines.h
    map.h
    mapreg.h
    mercenary.h
    messages_ad.h
    messages.h
    messages_main.h
    messages_re.h
    messages_sak.h
    messages_zero.h
    mob.h
    npc.h
    packets.h
    packets_keys_main.h
    packets_keys_zero.h
    packets_shuffle_main.h
    packets_shuffle_re.h
    packets_shuffle_zero.h
    packets_struct.h
    party.h
    path.h
    pc_groups.h
    pc.h
    pet.h
    quest.h
    refine.h
    refine.p.h
    rodex.h
    script.h
    searchstore.h
    skill.h
    status.h
    storage.h
    stylist.h
    trade.h
    unit.h
    vending.h
    )

target_link_libraries(map PCRE::PCRE)
target_link_libraries(map common)
target_link_libraries(map libconfig)
target_link_libraries(map mt19937ar)
target_link_libraries(map MySQL::MySQL)
target_link_libraries(map ZLIB::ZLIB)
target_link_libraries(map m)
target_link_libraries(map ${CMAKE_THREAD_LIBS_INIT})
target_link_libraries(map ${CMAKE_DL_LIBS})
